%% AERO3260 Assignment 1 - Task 2 (FINAL VERIFIED)
% Conformal mapping of a spinning cylinder to a Joukowsky aerofoil.
%
% SID = 550361509
% N7=5, N8=0, N9=9
% alpha = 15 deg
% z0 = -(N7+N8)/100 + i*N9/100 = -0.05 + 0.09i
%
% The assignment transformations are:
% z1 = z exp(i alpha)
% z2 = z1 + z0
% z3 = z2 + 1/z2
% z4 = z3 exp(-i alpha)
%
% The cylinder in the z2-plane is chosen to pass through the critical
% point z2=1, giving R=|1-z0|.

clear; close all; clc

%% Given quantities
N7=5; N8=0; N9=9;
Uinf=1;
alpha=15*pi/180;
z0=-(N7+N8)/100 + 1i*N9/100;

%% ================================================================
% TASK 2(a) - Cylinder radius
% ================================================================
R=abs(1-z0);

fprintf('\n================ TASK 2(a) ================\n');
fprintf('N7 = %d, N8 = %d, N9 = %d\n',N7,N8,N9);
fprintf('alpha = %.6f deg\n',rad2deg(alpha));
fprintf('z0 = %.6f %+.6fi\n',real(z0),imag(z0));
fprintf('Cylinder radius R = %.10f\n',R);
fprintf('Critical point = z2 = 1 + 0i\n');

%% ================================================================
% Geometry of shifted cylinder in z2-plane
% ================================================================
theta=linspace(0,2*pi,2000);
z2= z0 + R*exp(1i*theta);

% Inverse transformation to original cylinder z-plane:
% z2 = z*exp(i alpha)+z0
z = (z2-z0).*exp(-1i*alpha);

% Joukowsky transformation
z1=z.*exp(1i*alpha);
z2_check=z1+z0;
z3=z2_check+1./z2_check;
z4=z3.*exp(-1i*alpha);

% Transformation consistency check
fprintf('Transformation check max |z2-z2_check| = %.3e\n',...
    max(abs(z2-z2_check)));

figure('Color','w');
plot(real(z2),imag(z2),'k','LineWidth',2); hold on
plot(real(z0),imag(z0),'k+','MarkerSize',10,'LineWidth',1.5)
plot(1,0,'ko','MarkerFaceColor','w','MarkerSize',7)
axis equal; grid on; box on
xlabel('x_2'); ylabel('y_2')
title('Shifted Cylinder in the z_2-Plane')
legend('Cylinder surface','Cylinder centre','Critical point (1,0)',...
    'Location','best')

%% ================================================================
% TASK 2(b) - Spinning cylinder, Gamma = pi U R
% ================================================================
Gamma_b=pi*Uinf*R;

% Cylinder polar angle measured from its centre:
% V_theta = -2 U sin(theta) - Gamma/(2 pi R)
% Stagnation: sin(theta) = -Gamma/(4 pi U R) = -1/4
theta_stag1=asin(-Gamma_b/(4*pi*Uinf*R));
theta_stag2=pi-theta_stag1;

z2_stag1=z0+R*exp(1i*theta_stag1);
z2_stag2=z0+R*exp(1i*theta_stag2);

fprintf('\n================ TASK 2(b) ================\n');
fprintf('Assumed Gamma = pi Uinf R = %.10f\n',Gamma_b);
fprintf('Stagnation angle 1 = %.8f deg\n',rad2deg(theta_stag1));
fprintf('Stagnation angle 2 = %.8f deg\n',rad2deg(theta_stag2));
fprintf('Stagnation point 1 = %.8f %+.8fi\n',...
    real(z2_stag1),imag(z2_stag1));
fprintf('Stagnation point 2 = %.8f %+.8fi\n',...
    real(z2_stag2),imag(z2_stag2));

% Streamfunction of the spinning cylinder.
% The complex potential is written in the original z-plane.
zc=z;
psi_b=Uinf*imag(zc + R^2./zc + ...
    1i*Gamma_b/(2*pi*Uinf).*log(zc));

% For a flow-field plot, evaluate psi on a z2-plane Cartesian grid.
x2v=linspace(-2.4,2.4,700);
y2v=linspace(-2.2,2.2,650);
[X2,Y2]=meshgrid(x2v,y2v);

% z = (z2-z0) exp(-i alpha)
Z2=X2+1i*Y2;
Z=(Z2-z0).*exp(-1i*alpha);

Psi=Uinf*imag(Z + R^2./Z + ...
    1i*Gamma_b/(2*pi*Uinf).*log(Z));

% Mask the cylinder interior.
inside=abs(Z2-z0)<=R;
Psi(inside)=NaN;

figure('Color','w');
contour(X2,Y2,Psi,45,'LineWidth',0.75); hold on
plot(real(z2),imag(z2),'k','LineWidth',2.2)
plot(real([z2_stag1 z2_stag2]),imag([z2_stag1 z2_stag2]),...
    'ko','MarkerFaceColor','k','MarkerSize',6)
axis equal; xlim([-2.4 2.4]); ylim([-2.2 2.2])
grid on; box on
xlabel('x_2'); ylabel('y_2')
title('Spinning-Cylinder Flow in the z_2-Plane')
legend('Streamlines','Cylinder','Stagnation points',...
    'Location','best')

%% ================================================================
% TASK 2(c) - Kutta condition
% ================================================================
% The trailing edge is generated by the critical point z2=1.
% Its preimage in the original z-plane is:
z_TE=(1-z0).*exp(-1i*alpha);
theta_TE=angle(z_TE);

% For the cylinder surface:
% dw/dz = U(1-R^2/z^2) + i Gamma/(2 pi z)
% At the critical point the numerator must vanish.
% This gives:
% Gamma = -4 pi R U sin(theta_TE)
Gamma_Kutta=-4*pi*R*Uinf*sin(theta_TE);

z2_TE=1+0i;
z3_TE=z2_TE+1/z2_TE;
z4_TE=z3_TE*exp(-1i*alpha);

fprintf('\n================ TASK 2(c) ================\n');
fprintf('Cylinder TE preimage z_TE = %.10f %+.10fi\n',...
    real(z_TE),imag(z_TE));
fprintf('theta_TE = %.8f deg\n',rad2deg(theta_TE));
fprintf('Kutta circulation Gamma = %.10f\n',Gamma_Kutta);
fprintf('Mapped trailing edge z4_TE = %.10f %+.10fi\n',...
    real(z4_TE),imag(z4_TE));

% Generate transformed aerofoil.
z2a=z0+R*exp(1i*theta);
z1a=z2a;
za=(z1a-z0).*exp(-1i*alpha);
z3a=z2a+1./z2a;
z4a=z3a.*exp(-1i*alpha);

% Mark stagnation points after mapping for visual Kutta verification.
% The rear stagnation point is the one at the TE when Gamma=Gamma_Kutta.
figure('Color','w');
plot(real(z4a),imag(z4a),'k','LineWidth',2); hold on
plot(real(z4_TE),imag(z4_TE),'ro','MarkerFaceColor','r','MarkerSize',7)
axis equal; grid on; box on
xlabel('x_4'); ylabel('y_4')
title('Joukowsky Aerofoil with Kutta Condition')
legend('Aerofoil surface','Trailing edge / rear stagnation point',...
    'Location','best')

%% ================================================================
% Verify Kutta condition directly
% ================================================================
dwdz_TE=Uinf*(1-R^2/z_TE^2 + ...
    1i*Gamma_Kutta/(2*pi*Uinf*z_TE));

fprintf('Kutta numerator |dw/dz| at TE = %.3e\n',abs(dwdz_TE));

%% ================================================================
% TASK 2(d) - Pressure coefficient
% ================================================================
% The physical aerofoil surfaces are separated by the cylinder parameter
% intervals between the trailing-edge preimage and leading-edge preimage.
% Surface classification is made relative to the aerofoil chord, NOT by
% global y4, because the aerofoil is rotated by alpha.
%
% The Joukowsky mapping has critical points at z2 = +1 and z2 = -1.
% The Kutta condition removes the trailing-edge singularity at z2 = +1.
% The inviscid leading-edge velocity remains singular, so Cp tends to
% -infinity as the exact leading edge is approached.  The plot therefore
% omits only a tiny neighbourhood of the leading edge.

Gamma = Gamma_Kutta;

% Dense cylinder parameter
thetaCp=linspace(0,2*pi,40001);
z2Cp=z0+R*exp(1i*thetaCp);
zCp=(z2Cp-z0).*exp(-1i*alpha);
z4Cp=(z2Cp+1./z2Cp).*exp(-1i*alpha);

% Complex velocity in physical z4 plane
dwdz=Uinf*(1-R^2./zCp.^2 + ...
    1i*Gamma./(2*pi*Uinf*zCp));
denom=1-1./z2Cp.^2;

% Avoid the exact critical points in the numerical evaluation.
valid=abs(z2Cp-1)>1e-7 & abs(z2Cp+1)>1e-7;

VJ_complex=dwdz(valid)./denom(valid);
CpAll=1-abs(VJ_complex/Uinf).^2;
z4All=z4Cp(valid);
z2All=z2Cp(valid);
thetaAll=thetaCp(valid);

% ----------------------------------------------------------------
% Physical chord geometry
% ----------------------------------------------------------------
z2_LE=-1+0i;
z2_TE= 1+0i;

z4_LE=(z2_LE+1/z2_LE)*exp(-1i*alpha);
z4_TE=(z2_TE+1/z2_TE)*exp(-1i*alpha);

chordVec=z4_TE-z4_LE;
c=abs(chordVec);
eChord=chordVec/c;

% Positive normal corresponds to the upper side of the aerofoil.
eNormal=[-imag(eChord), real(eChord)];

% Coordinates measured from leading edge:
dr=z4All-z4_LE;
xc=real(dr*conj(eChord))/c;
yc=real(dr)*eNormal(1)+imag(dr)*eNormal(2);

% Small leading-edge exclusion for a finite, readable Cp plot.
LE_plot_cut=0.005;
plotValid=xc>=LE_plot_cut & xc<=1+1e-10;

% ----------------------------------------------------------------
% Correct physical surface identification
% ----------------------------------------------------------------
% IMPORTANT: Do NOT classify the two aerofoil surfaces using the sign
% of yc.  The mapped aerofoil is cambered, so the lower surface can
% lie above the chord line over part of the chord.  The two physical
% surfaces are instead identified by the two arcs of the cylinder
% between the leading-edge and trailing-edge preimages.

% Cylinder-plane polar angles of the two critical points.
theta_TE_cyl = mod(angle(1-z0),2*pi);
theta_LE_cyl = mod(angle(-1-z0),2*pi);

% For this mapping, the arc containing theta=0 maps to the upper
% aerofoil surface, while the complementary arc maps to the lower
% surface.  With the present geometry: LE = 185.41 deg,
% TE = 355.10 deg in the z2-plane.
lowerArc = (thetaAll >= theta_LE_cyl) & (thetaAll <= theta_TE_cyl);
upperArc = ~lowerArc;

upper = upperArc & plotValid;
lower = lowerArc & plotValid;

xu=xc(upper); cpu=CpAll(upper);
xl=xc(lower); cpl=CpAll(lower);

% Sort each physical surface from leading edge to trailing edge.
[xu,iu]=sort(xu); cpu=cpu(iu);
[xl,il]=sort(xl); cpl=cpl(il);

fprintf('\n================ TASK 2(d) ================\n');
fprintf('Chord length c = %.10f\n',c);
fprintf('Leading edge z4_LE = %.10f %+.10fi\n',real(z4_LE),imag(z4_LE));
fprintf('Trailing edge z4_TE = %.10f %+.10fi\n',real(z4_TE),imag(z4_TE));
fprintf('Leading-edge plot cut x/c = %.4f\n',LE_plot_cut);
fprintf('Cylinder LE angle = %.8f deg\n',rad2deg(theta_LE_cyl));
fprintf('Cylinder TE angle = %.8f deg\n',rad2deg(theta_TE_cyl));
fprintf('Upper-surface points = %d\n',numel(cpu));
fprintf('Lower-surface points = %d\n',numel(cpl));
fprintf('Finite Cp check = %d\n',all(isfinite([cpu(:);cpl(:)])));

CpPlot=[cpu(:); cpl(:)];
fprintf('Finite plotted Cp minimum = %.8f\n',min(CpPlot));
fprintf('Finite plotted Cp maximum = %.8f\n',max(CpPlot));

% Values closest to the trailing edge on each surface
fprintf('Upper-surface TE Cp = %.8f\n',cpu(end));
fprintf('Lower-surface TE Cp = %.8f\n',cpl(end));
fprintf('TE Cp difference = %.3e\n',abs(cpu(end)-cpl(end)));

% Direct Kutta check at the cylinder preimage
dwdz_TE=Uinf*(1-R^2/z_TE^2 + ...
    1i*Gamma/(2*pi*Uinf*z_TE));
fprintf('Direct Kutta check |dw/dz| at TE = %.3e\n',abs(dwdz_TE));

%% Report-quality Cp plot in x/c coordinates
figure('Color','w');
plot(xu,cpu,'LineWidth',1.5); hold on
plot(xl,cpl,'LineWidth',1.5)
set(gca,'YDir','reverse')
grid on; box on
xlabel('x/c','FontSize',12)
ylabel('C_p','FontSize',12)
title('Joukowsky Aerofoil Pressure Distribution, \alpha = 15^\circ')
legend('Upper surface','Lower surface','Location','best')
xlim([0 1])

%% Final aerofoil geometry in chord coordinates
% Convert mapped coordinates into chord-normalised coordinates.
drAll=z4Cp-z4_LE;
xGeom=real(drAll*conj(eChord))/c;
yGeom=real(drAll)*eNormal(1)+imag(drAll)*eNormal(2);

figure('Color','w');
plot(xGeom,yGeom,'k','LineWidth',2); hold on
plot(1,0,'ro','MarkerFaceColor','r','MarkerSize',7)
axis equal; grid on; box on
xlabel('x/c','FontSize',12)
ylabel('y/c','FontSize',12)
title('Final Joukowsky Aerofoil Geometry')
legend('Aerofoil surface','Trailing edge','Location','best')
xlim([-0.02 1.02])

fprintf('============================================\n\n');
